name: marvel_characters
description: List of Marvel characters
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.2

dependencies:
  api_client:
    path: ../../utility/api_client
  tide_design_system:
    path: ../../utility/tide_design_system
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  injectable: ^2.3.2
  tide_monitoring:
    path: ../../utility/tide_monitoring
  tide_prelude:
    path: ../../utility/tide_prelude
  retrofit: ^4.0.3
  tide_di:
    path: ../../utility/tide_di

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.5
  tide_analysis:
    path: ../../utility/tide_analysis