name: api_client
description: Marvel API client
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  crypto: ^3.0.3
  dio: ^5.4.0
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  tide_prelude:
    path: ../tide_prelude
  retrofit: ^4.0.3
  tide_di:
    path: ../tide_di

dev_dependencies:
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  tide_analysis:
    path: ../../utility/tide_analysis